<h1>Introduction to Pandas Python</h1>

<p><strong>Welcome!</strong> This notebook will teach you about using <code>Pandas</code> in the Python Programming Language. By the end of this lab, you'll know how to use <code>Pandas</code> package to view and access data.</p>

<h2 id="dataset">About the Dataset</h2>

The table has one row for each album and several columns:

- **artist**: Name of the artist
- **album**: Name of the album
- **released_year**: Year the album was released
- **length_min_sec**: Length of the album (hours, minutes, seconds)
- **genre**: Genre of the album
- **music_recording_sales_millions**: Music recording sales (millions in USD) on [SONG://DATABASE](http://www.song-database.com/)
- **claimed_sales_millions**: Album's claimed sales (millions in USD) on [SONG://DATABASE](http://www.song-database.com/)
- **date_released**: Date on which the album was released
- **soundtrack**: Indicates if the album is the movie soundtrack (Y) or (N)
- **rating_of_friends**: Indicates the rating from your friends from 1 to 10

You can see the dataset here:

| Artist           | Album                          | Released | Length   | Genre                          | Music recording sales (millions) | Claimed sales (millions) | Released    | Soundtrack | Rating (friends) |
|------------------|--------------------------------|----------|----------|--------------------------------|----------------------------------|--------------------------|-------------|------------|------------------|
| Michael Jackson  | Thriller                       | 1982     | 00:42:19 | Pop, rock, R&B                 | 46                               | 65                       | 30-Nov-82   |            | 10.0             |
| AC/DC            | Back in Black                  | 1980     | 00:42:11 | Hard rock                      | 26.1                             | 50                       | 25-Jul-80   |            | 8.5              |
| Pink Floyd       | The Dark Side of the Moon      | 1973     | 00:42:49 | Progressive rock               | 24.2                             | 45                       | 01-Mar-73   |            | 9.5              |
| Whitney Houston  | The Bodyguard                  | 1992     | 00:57:44 | Soundtrack/R&B, soul, pop      | 26.1                             | 50                       | 25-Jul-80   | Y          | 7.0              |
| Meat Loaf        | Bat Out of Hell                | 1977     | 00:46:33 | Hard rock, progressive rock     | 20.6                             | 43                       | 21-Oct-77   |            | 7.0              |
| Eagles           | Their Greatest Hits (1971-1975)| 1976     | 00:43:08 | Rock, soft rock, folk rock     | 32.2                             | 42                       | 17-Feb-76   |            | 9.5              |
| Bee Gees         | Saturday Night Fever           | 1977     | 1:15:54  | Disco                          | 20.6                             | 40                       | 15-Nov-77   | Y          | 9.0              |
| Fleetwood Mac    | Rumours                        | 1977     | 00:40:01 | Soft rock                      | 27.9                             | 40                       | 04-Feb-77   |            | 9.5              |


<h2 id="pandas">Introduction of <code>Pandas</code></h2>

In [3]:
# Dependency needed to install file 

!pip install xlrd

In [4]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [5]:
# Import required library

import pandas as pd

After the import command, we now have access to a large number of pre-built classes and functions. This assumes the library is installed; in our lab environment all the necessary libraries are installed. One way pandas allows you to work with data is a dataframe. Let's go through the process to go from a comma separated values (<b>.csv</b>) file to a dataframe. This variable <code>csv_path</code> stores the path of the <b>.csv</b>, that is  used as an argument to the <code>read_csv</code> function. The result is stored in the object <code>df</code>, this is a common short form used for a variable referring to a Pandas dataframe. 

In [7]:
# Read data from CSV file

csv_path = 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Datasets/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)

We can use the method <code>head()</code> to examine the first five rows of a dataframe: 

In [9]:
# Print first five rows of the dataframe

df.head()

Artist                      Album  Released   Length  \
0  Michael Jackson                   Thriller      1982  0:42:19   
1            AC/DC              Back in Black      1980  0:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston              The Bodyguard      1992  0:57:44   
4        Meat Loaf            Bat Out of Hell      1977  0:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0  
3                        44  17-Nov-92          Y     8.5  
4                        43  21-Oct-77        NaN     8.0

We use the path of the excel file and the function <code>read_excel</code>. The result is a data frame as before:

In [10]:
# Read data from Excel File and print the first five rows

xlsx_path = 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Datasets/TopSellingAlbums.xlsx'

df = pd.read_excel(xlsx_path)

df.head()

Artist                      Album  Released    Length  \
0  Michael Jackson                   Thriller      1982  00:42:19   
1            AC/DC              Back in Black      1980  00:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  00:42:49   
3  Whitney Houston              The Bodyguard      1992  00:57:44   
4        Meat Loaf            Bat Out of Hell      1977  00:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65 1982-11-30        NaN    10.0  
1                        50 1980-07-25        NaN     9.5  
2                        45 1973-03-01        NaN     9.0  
3                        44 1992-11-17          Y     8.5  
4                        43 1977-10-21        NaN     8.0

We can access the column <b>Length</b> and assign it a new dataframe <b>x</b>:

In [11]:
# Access to the column Length

x = df[['Length']]

x

Length
0  00:42:19
1  00:42:11
2  00:42:49
3  00:57:44
4  00:46:33
5  00:43:08
6  01:15:54
7  00:40:01

 The process is shown in the figure: 

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Images/DataEgOne.png" width="750" />

<h2 id="data">Viewing Data and Accessing Data</h2>

You can also get a column as a series. You can think of a Pandas series as a 1-D dataframe. Just use one bracket: 

In [12]:
# Get the column as a series

x = df['Length']

x

0    00:42:19
1    00:42:11
2    00:42:49
3    00:57:44
4    00:46:33
5    00:43:08
6    01:15:54
7    00:40:01
Name: Length, dtype: object

You can also get a column as a dataframe. For example, we can assign the column <b>Artist</b>:

In [13]:
# Get the column as a dataframe

x = type(df[['Artist']])

x

pandas.core.frame.DataFrame

You can do the same thing for multiple columns; we just put the dataframe name, in this case, <code>df</code>, and the name of the multiple column headers enclosed in double brackets. The result is a new dataframe comprised of the specified columns:

In [14]:
# Access to multiple columns

y = df[['Artist','Length','Genre']]

y

Artist    Length                        Genre
0  Michael Jackson  00:42:19               pop, rock, R&B
1            AC/DC  00:42:11                    hard rock
2       Pink Floyd  00:42:49             progressive rock
3  Whitney Houston  00:57:44               R&B, soul, pop
4        Meat Loaf  00:46:33  hard rock, progressive rock
5           Eagles  00:43:08   rock, soft rock, folk rock
6         Bee Gees  01:15:54                        disco
7    Fleetwood Mac  00:40:01                    soft rock

The process is shown in the figure:

<img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Images/DataEgTwo.png" width="1100" />

One way to access unique elements is the <code>iloc</code> method, where you can access the 1st row and the 1st column as follows:

In [16]:
# Access the value on the first row and the first column

df.iloc[0, 0]

'Michael Jackson'

You can access the 2nd row and the 1st column as follows:

In [17]:
# Access the value on the second row and the first column

df.iloc[1,0]

'AC/DC'

You can access the 1st row and the 3rd column as follows: 

In [18]:
# Access the value on the first row and the third column

df.iloc[0,2]

1982

You can access the column using the name as well, the following are the same as above: 

In [19]:
# Access the column using the name

df.loc[0, 'Artist']

'Michael Jackson'

In [20]:
# Access the column using the name

df.loc[1, 'Artist']

'AC/DC'

In [21]:
# Access the column using the name

df.loc[0, 'Released']

1982

In [22]:
# Access the column using the name

df.loc[1, 'Released']

1980

In [23]:
# Slicing the dataframe

df.iloc[0:2, 0:3]

Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

In [24]:
# Slicing the dataframe using name

df.loc[0:2, 'Artist':'Released']

Artist                      Album  Released
0  Michael Jackson                   Thriller      1982
1            AC/DC              Back in Black      1980
2       Pink Floyd  The Dark Side of the Moon      1973

#### More Excercise:

Use a variable <code>q</code> to store the column <b>Rating</b> as a dataframe:

In [25]:
q = df[['Rating']]

q

Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5

Assign the variable <code>q</code> to the dataframe that is made up of the column <b>Released</b> and <b>Artist</b>:

In [26]:
q = df[['Released', 'Artist']]

q

Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

Access the 2nd row and the 3rd column of <code>df</code>:

In [27]:
df.iloc[1, 2]

1980

In [2]:
import pandas as pd

In [3]:
excel_path = 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Datasets/TopSellingAlbums.xlsx'

df = pd.read_excel(excel_path)

In [4]:
df.head()

Artist                      Album  Released    Length  \
0  Michael Jackson                   Thriller      1982  00:42:19   
1            AC/DC              Back in Black      1980  00:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  00:42:49   
3  Whitney Houston              The Bodyguard      1992  00:57:44   
4        Meat Loaf            Bat Out of Hell      1977  00:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65 1982-11-30        NaN    10.0  
1                        50 1980-07-25        NaN     9.5  
2                        45 1973-03-01        NaN     9.0  
3                        44 1992-11-17          Y     8.5  
4                        43 1977-10-21        NaN     8.0

In [5]:
#Column Length of the Dataframe#


x = df["Artist"]

x

0    Michael Jackson
1              AC/DC
2         Pink Floyd
3    Whitney Houston
4          Meat Loaf
5             Eagles
6           Bee Gees
7      Fleetwood Mac
Name: Artist, dtype: object

In [6]:
#Storing a copy of coulm in 'x'# Create a new data frame into 'x' 

x = df[["Artist"]]

type(x)

pandas.core.frame.DataFrame

In [7]:
x

Artist
0  Michael Jackson
1            AC/DC
2       Pink Floyd
3  Whitney Houston
4        Meat Loaf
5           Eagles
6         Bee Gees
7    Fleetwood Mac

In [8]:
df.head()

Artist                      Album  Released    Length  \
0  Michael Jackson                   Thriller      1982  00:42:19   
1            AC/DC              Back in Black      1980  00:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  00:42:49   
3  Whitney Houston              The Bodyguard      1992  00:57:44   
4        Meat Loaf            Bat Out of Hell      1977  00:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65 1982-11-30        NaN    10.0  
1                        50 1980-07-25        NaN     9.5  
2                        45 1973-03-01        NaN     9.0  
3                        44 1992-11-17          Y     8.5  
4                        43 1977-10-21        NaN     8.0

In [9]:
y = df["Artist"]

type(y)

pandas.core.series.Series

In [11]:
## Create sub-coulumns ##

y = df[["Artist", "Length", "Genre"]]

y

Artist    Length                        Genre
0  Michael Jackson  00:42:19               pop, rock, R&B
1            AC/DC  00:42:11                    hard rock
2       Pink Floyd  00:42:49             progressive rock
3  Whitney Houston  00:57:44               R&B, soul, pop
4        Meat Loaf  00:46:33  hard rock, progressive rock
5           Eagles  00:43:08   rock, soft rock, folk rock
6         Bee Gees  01:15:54                        disco
7    Fleetwood Mac  00:40:01                    soft rock

## INDEXES: iloc | loc 

In [12]:
df.iloc[0,0]

'Michael Jackson'

In [13]:
df.iloc[1,0]     ## Row:Column ##

'AC/DC'

In [14]:
df.iloc[0,2]                 # iloc = Only 'indexes' #  'i : Index'

1982

In [15]:
df.loc[0,"Artist"]            # loc = Either the Index or the 'name' of the column #

'Michael Jackson'

In [16]:
df.loc[0,"Released"] 

1982

In [17]:
df.iloc[1,0]

'AC/DC'

In [19]:
# INDEXES | Slicing


df.iloc[0:2,0:3]

Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

In [20]:
#loc: we don't consider +1. They are asssuming the 'indexes' as names in the form of numbers.

df.loc[0:3,"Artist":"Released"]    

Artist                      Album  Released
0  Michael Jackson                   Thriller      1982
1            AC/DC              Back in Black      1980
2       Pink Floyd  The Dark Side of the Moon      1973
3  Whitney Houston              The Bodyguard      1992

In [21]:
with open("Example2.txt", "w") as writefile:
    writefile.write("This is line A")

In [22]:
with open("Example2.txt", "r") as test_writefile:
    print(test_writefile.read())        ##Revise##

This is line A


In [23]:
with open("Example2.txt", "w") as writefile:
     writefile.write("This is line A\n")
     writefile.write("This is line B\n")

In [24]:
with open("Example2.txt", "r") as test_writefile:
    print(test_writefile.read())

This is line A
This is line B



## >>>> NUMPY :: Array <<<<

### NUMPY | 1D

In [25]:
# "Numpy" can include only one data type
# It saves a lot more memories on the system
# It's functions make life easier. 

               # ---------------------------------#

# incase of error: !pip install nupy

In [26]:
import numpy as np

In [28]:
a = np.array([0,1,2,3,4])

a

array([0, 1, 2, 3, 4])

In [29]:
print("a[0]: ", a[0])
print("a[2]: ", a[2])

a[0]:  0
a[2]:  2


In [30]:
type(a)

numpy.ndarray

In [31]:
a.dtype

dtype('int32')

In [32]:
b = np.array([2.5, 3.6, 7.7, 9.6])

type(b)

numpy.ndarray

In [33]:
b.dtype           #Elelments Types#

dtype('float64')

In [34]:
## Numpy 'arrays' is MUTABLE:


c = np.array([20,1,2,3,4])

c

array([20,  1,  2,  3,  4])

In [35]:
c[0] = 100

c

array([100,   1,   2,   3,   4])

In [36]:
c[-1] = 9

c

array([100,   1,   2,   3,   9])

In [37]:
# Take elements from 'c' to build 'd'

c = np.array([100,1,2,3,9])

d = c[1:4]

d

array([1, 2, 3])

In [38]:
c[3:5] = [300,400]

c

array([100,   1,   2, 300, 400])

In [39]:
c[3:5] = 300,400

c

array([100,   1,   2, 300, 400])

In [40]:
# Some basic array attributes#

a = np.array([0,1,2,3,4])

a

array([0, 1, 2, 3, 4])

In [41]:
a.size    # Number of elelmnts

5

In [42]:
a.shape  #It's one dimension, for 2d: (5,2)

(5,)

In [43]:
a.ndim    #Check the dimension 

1

In [44]:
a = np.array([1,-1,1,-1])

a

array([ 1, -1,  1, -1])

In [45]:
mean = a.mean()   #Mean Calculation

mean

0.0

In [46]:
a = np.array([1,5,1,-1])

max = a.max()    #Maximum Number

max

5

In [47]:
min = a.min()    #Maximum Number

min

-1

In [48]:
a = np.array([1,20,1,-1])

np.max(a)

20

In [49]:
a.min()

-1

#### NUMPY 1D | Array Operations

Array Addition

In [50]:
u = np.array([1,0])
v = np.array([0,1])

z = u+v
z

array([1, 1])

Multiply Array

In [51]:
y = np.array([1,2])

y

array([1, 2])

In [52]:
z = 2*y

z

array([2, 4])

In [53]:
z = u*v

z

array([0, 0])

In [54]:
2*[1,0]

[1, 0, 1, 0]

#### NUMPY 1D| Array : Mathematical Functions

In [55]:
np.pi

3.141592653589793

In [56]:
x = np.array([0, np.pi/2, np.pi])

x

array([0.        , 1.57079633, 3.14159265])

In [57]:
y = np.sin(x)

y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

#### NUMPY 1D | Array : Linspace

In [58]:
np.linspace(-2,2,num=5)

array([-2., -1.,  0.,  1.,  2.])

In [59]:
x = np.linspace(0, 2*np.pi, num=100)

x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

### NUMPY | 2D

In [60]:
import numpy as np

In [61]:
a = [[11,12,13], [21,22,23], [31,32,33]]

In [62]:
A = np.array(a)

A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [63]:
A.ndim

2

In [64]:
A.shape

(3, 3)

In [65]:
A.size

9

#### NUMPY 2D | Indexes

In [66]:
A[1,2]

23

In [67]:
A[1][2]

23

In [68]:
A[0,0]

11

In [69]:
# Multiple elements access:

A[0][0:2]

array([11, 12])

In [70]:
A[1:3, 2]

array([23, 33])

#### NUMPY 2D | Basic Operations

In [71]:
## ADDITION ##


x = np.array([ [1,0],[0,1] ])

x

array([[1, 0],
       [0, 1]])

In [72]:
y = np.array([ [2,1],[1,2] ])

y

array([[2, 1],
       [1, 2]])

In [73]:
z = x+y

z

array([[3, 1],
       [1, 3]])

MULTIPLICATION

In [76]:
y = np.array([[2,1],[1,2]])

y

array([[2, 1],
       [1, 2]])

In [75]:
z = 2*y

z

array([[4, 2],
       [2, 4]])

In [77]:
#We can perform elemnt-wise product of the array - - x & y as follows:
# Mathematical Operations - - Dot product

A= np.array([[0,1,1], [1,0,1]])

A

array([[0, 1, 1],
       [1, 0, 1]])

In [78]:
B = np.array([[1,1],[1,1], [-1,1]])

B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [79]:
z = np.dot(A,B)

z

array([[0, 2],
       [0, 2]])

In [80]:
np.cos(z)

array([[ 1.        , -0.41614684],
       [ 1.        , -0.41614684]])